export const SAVE_ADMIN_REQUEST = 'user:SAVE_ADMIN_REQUEST';
export const SAVE_ADMIN_SUCCESS = 'user:SAVE_ADMIN_SUCCESS';
export const SAVE_ADMIN_FAILURE = 'user:SAVE_ADMIN_FAILURE';

export const SAVE_MEMBER_REQUEST = 'user:SAVE_MEMBER_REQUEST';
export const SAVE_MEMBER_SUCCESS = 'user:SAVE_MEMBER_SUCCESS';
export const SAVE_MEMBER_FAILURE = 'user:SAVE_MEMBER_FAILURE';
