export const CLEAN_UP = 'user:CLEAN_UP';

export const SAVE_USER_REQUEST = 'user:SAVE_USER_REQUEST';
export const SAVE_USER_SUCCESS = 'user:SAVE_USER_SUCCESS';
export const SAVE_USER_FAILURE = 'user:SAVE_USER_FAILURE';

export const LOAD_USERS_REQUEST = 'user:LOAD_USERS_REQUEST';
export const LOAD_USERS_SUCCESS = 'user:LOAD_USERS_SUCCESS';
export const LOAD_USERS_FAILURE = 'user:LOAD_USERS_FAILURE';

export const DELETE_CREW_USER_REQUEST = 'user:DELETE_CREW_USER_REQUEST';
export const DELETE_CREW_USER_SUCCESS = 'user:DELETE_CREW_USER_SUCCESS';
export const DELETE_CREW_USER_FAILURE = 'user:DELETE_CREW_USER_FAILURE';
